/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinShareRouteImport } from './routes/join-share'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteRouteImport } from './routes/_account/route'
import { Route as AccountIndexRouteImport } from './routes/_account/index'
import { Route as AccountSettingsRouteImport } from './routes/_account/settings'
import { Route as AccountJoinRouteImport } from './routes/_account/join'
import { Route as AccountAccountRouteImport } from './routes/_account/account'
import { Route as AccountSSchoolIdRouteRouteImport } from './routes/_account/s.$schoolId/route'
import { Route as AccountCClassIdRouteRouteImport } from './routes/_account/c.$classId/route'
import { Route as AccountSSchoolIdIndexRouteImport } from './routes/_account/s.$schoolId/index'
import { Route as AccountCClassIdIndexRouteImport } from './routes/_account/c.$classId/index'
import { Route as AccountSSchoolIdTeamsRouteImport } from './routes/_account/s.$schoolId/teams'
import { Route as AccountSSchoolIdTeachersRouteImport } from './routes/_account/s.$schoolId/teachers'
import { Route as AccountSSchoolIdSettingsRouteImport } from './routes/_account/s.$schoolId/settings'
import { Route as AccountSSchoolIdPrincipalsRouteImport } from './routes/_account/s.$schoolId/principals'
import { Route as AccountSSchoolIdMembersRouteImport } from './routes/_account/s.$schoolId/members'
import { Route as AccountSSchoolIdInviteRouteImport } from './routes/_account/s.$schoolId/invite'
import { Route as AccountSSchoolIdClassesRouteImport } from './routes/_account/s.$schoolId/classes'
import { Route as AccountSSchoolIdAdminsRouteImport } from './routes/_account/s.$schoolId/admins'
import { Route as AccountCClassIdTeachersRouteImport } from './routes/_account/c.$classId/teachers'
import { Route as AccountCClassIdStudentsRouteImport } from './routes/_account/c.$classId/students'
import { Route as AccountCClassIdSettingsRouteImport } from './routes/_account/c.$classId/settings'
import { Route as AccountCClassIdPointsRouteImport } from './routes/_account/c.$classId/points'
import { Route as AccountCClassIdMembersRouteImport } from './routes/_account/c.$classId/members'
import { Route as AccountCClassIdInviteRouteImport } from './routes/_account/c.$classId/invite'
import { Route as AccountCClassIdGuardiansRouteImport } from './routes/_account/c.$classId/guardians'
import { Route as AccountCClassIdGroupsRouteImport } from './routes/_account/c.$classId/groups'
import { Route as AccountCClassIdAssistantTeachersRouteImport } from './routes/_account/c.$classId/assistant-teachers'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinShareRoute = JoinShareRouteImport.update({
  id: '/join-share',
  path: '/join-share',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountJoinRoute = AccountJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAccountRoute = AccountAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSSchoolIdRouteRoute = AccountSSchoolIdRouteRouteImport.update({
  id: '/s/$schoolId',
  path: '/s/$schoolId',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountCClassIdRouteRoute = AccountCClassIdRouteRouteImport.update({
  id: '/c/$classId',
  path: '/c/$classId',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSSchoolIdIndexRoute = AccountSSchoolIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountSSchoolIdRouteRoute,
} as any)
const AccountCClassIdIndexRoute = AccountCClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountSSchoolIdTeamsRoute = AccountSSchoolIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AccountSSchoolIdRouteRoute,
} as any)
const AccountSSchoolIdTeachersRoute =
  AccountSSchoolIdTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AccountSSchoolIdRouteRoute,
  } as any)
const AccountSSchoolIdSettingsRoute =
  AccountSSchoolIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AccountSSchoolIdRouteRoute,
  } as any)
const AccountSSchoolIdPrincipalsRoute =
  AccountSSchoolIdPrincipalsRouteImport.update({
    id: '/principals',
    path: '/principals',
    getParentRoute: () => AccountSSchoolIdRouteRoute,
  } as any)
const AccountSSchoolIdMembersRoute = AccountSSchoolIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AccountSSchoolIdRouteRoute,
} as any)
const AccountSSchoolIdInviteRoute = AccountSSchoolIdInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AccountSSchoolIdRouteRoute,
} as any)
const AccountSSchoolIdClassesRoute = AccountSSchoolIdClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AccountSSchoolIdRouteRoute,
} as any)
const AccountSSchoolIdAdminsRoute = AccountSSchoolIdAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AccountSSchoolIdRouteRoute,
} as any)
const AccountCClassIdTeachersRoute = AccountCClassIdTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdStudentsRoute = AccountCClassIdStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdSettingsRoute = AccountCClassIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdPointsRoute = AccountCClassIdPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdMembersRoute = AccountCClassIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdInviteRoute = AccountCClassIdInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdGuardiansRoute =
  AccountCClassIdGuardiansRouteImport.update({
    id: '/guardians',
    path: '/guardians',
    getParentRoute: () => AccountCClassIdRouteRoute,
  } as any)
const AccountCClassIdGroupsRoute = AccountCClassIdGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdAssistantTeachersRoute =
  AccountCClassIdAssistantTeachersRouteImport.update({
    id: '/assistant-teachers',
    path: '/assistant-teachers',
    getParentRoute: () => AccountCClassIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AccountIndexRoute
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AccountAccountRoute
  '/join': typeof AccountJoinRoute
  '/settings': typeof AccountSettingsRoute
  '/c/$classId': typeof AccountCClassIdRouteRouteWithChildren
  '/s/$schoolId': typeof AccountSSchoolIdRouteRouteWithChildren
  '/c/$classId/assistant-teachers': typeof AccountCClassIdAssistantTeachersRoute
  '/c/$classId/groups': typeof AccountCClassIdGroupsRoute
  '/c/$classId/guardians': typeof AccountCClassIdGuardiansRoute
  '/c/$classId/invite': typeof AccountCClassIdInviteRoute
  '/c/$classId/members': typeof AccountCClassIdMembersRoute
  '/c/$classId/points': typeof AccountCClassIdPointsRoute
  '/c/$classId/settings': typeof AccountCClassIdSettingsRoute
  '/c/$classId/students': typeof AccountCClassIdStudentsRoute
  '/c/$classId/teachers': typeof AccountCClassIdTeachersRoute
  '/s/$schoolId/admins': typeof AccountSSchoolIdAdminsRoute
  '/s/$schoolId/classes': typeof AccountSSchoolIdClassesRoute
  '/s/$schoolId/invite': typeof AccountSSchoolIdInviteRoute
  '/s/$schoolId/members': typeof AccountSSchoolIdMembersRoute
  '/s/$schoolId/principals': typeof AccountSSchoolIdPrincipalsRoute
  '/s/$schoolId/settings': typeof AccountSSchoolIdSettingsRoute
  '/s/$schoolId/teachers': typeof AccountSSchoolIdTeachersRoute
  '/s/$schoolId/teams': typeof AccountSSchoolIdTeamsRoute
  '/c/$classId/': typeof AccountCClassIdIndexRoute
  '/s/$schoolId/': typeof AccountSSchoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AccountAccountRoute
  '/join': typeof AccountJoinRoute
  '/settings': typeof AccountSettingsRoute
  '/': typeof AccountIndexRoute
  '/c/$classId/assistant-teachers': typeof AccountCClassIdAssistantTeachersRoute
  '/c/$classId/groups': typeof AccountCClassIdGroupsRoute
  '/c/$classId/guardians': typeof AccountCClassIdGuardiansRoute
  '/c/$classId/invite': typeof AccountCClassIdInviteRoute
  '/c/$classId/members': typeof AccountCClassIdMembersRoute
  '/c/$classId/points': typeof AccountCClassIdPointsRoute
  '/c/$classId/settings': typeof AccountCClassIdSettingsRoute
  '/c/$classId/students': typeof AccountCClassIdStudentsRoute
  '/c/$classId/teachers': typeof AccountCClassIdTeachersRoute
  '/s/$schoolId/admins': typeof AccountSSchoolIdAdminsRoute
  '/s/$schoolId/classes': typeof AccountSSchoolIdClassesRoute
  '/s/$schoolId/invite': typeof AccountSSchoolIdInviteRoute
  '/s/$schoolId/members': typeof AccountSSchoolIdMembersRoute
  '/s/$schoolId/principals': typeof AccountSSchoolIdPrincipalsRoute
  '/s/$schoolId/settings': typeof AccountSSchoolIdSettingsRoute
  '/s/$schoolId/teachers': typeof AccountSSchoolIdTeachersRoute
  '/s/$schoolId/teams': typeof AccountSSchoolIdTeamsRoute
  '/c/$classId': typeof AccountCClassIdIndexRoute
  '/s/$schoolId': typeof AccountSSchoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_account': typeof AccountRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_account/account': typeof AccountAccountRoute
  '/_account/join': typeof AccountJoinRoute
  '/_account/settings': typeof AccountSettingsRoute
  '/_account/': typeof AccountIndexRoute
  '/_account/c/$classId': typeof AccountCClassIdRouteRouteWithChildren
  '/_account/s/$schoolId': typeof AccountSSchoolIdRouteRouteWithChildren
  '/_account/c/$classId/assistant-teachers': typeof AccountCClassIdAssistantTeachersRoute
  '/_account/c/$classId/groups': typeof AccountCClassIdGroupsRoute
  '/_account/c/$classId/guardians': typeof AccountCClassIdGuardiansRoute
  '/_account/c/$classId/invite': typeof AccountCClassIdInviteRoute
  '/_account/c/$classId/members': typeof AccountCClassIdMembersRoute
  '/_account/c/$classId/points': typeof AccountCClassIdPointsRoute
  '/_account/c/$classId/settings': typeof AccountCClassIdSettingsRoute
  '/_account/c/$classId/students': typeof AccountCClassIdStudentsRoute
  '/_account/c/$classId/teachers': typeof AccountCClassIdTeachersRoute
  '/_account/s/$schoolId/admins': typeof AccountSSchoolIdAdminsRoute
  '/_account/s/$schoolId/classes': typeof AccountSSchoolIdClassesRoute
  '/_account/s/$schoolId/invite': typeof AccountSSchoolIdInviteRoute
  '/_account/s/$schoolId/members': typeof AccountSSchoolIdMembersRoute
  '/_account/s/$schoolId/principals': typeof AccountSSchoolIdPrincipalsRoute
  '/_account/s/$schoolId/settings': typeof AccountSSchoolIdSettingsRoute
  '/_account/s/$schoolId/teachers': typeof AccountSSchoolIdTeachersRoute
  '/_account/s/$schoolId/teams': typeof AccountSSchoolIdTeamsRoute
  '/_account/c/$classId/': typeof AccountCClassIdIndexRoute
  '/_account/s/$schoolId/': typeof AccountSSchoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/account'
    | '/join'
    | '/settings'
    | '/c/$classId'
    | '/s/$schoolId'
    | '/c/$classId/assistant-teachers'
    | '/c/$classId/groups'
    | '/c/$classId/guardians'
    | '/c/$classId/invite'
    | '/c/$classId/members'
    | '/c/$classId/points'
    | '/c/$classId/settings'
    | '/c/$classId/students'
    | '/c/$classId/teachers'
    | '/s/$schoolId/admins'
    | '/s/$schoolId/classes'
    | '/s/$schoolId/invite'
    | '/s/$schoolId/members'
    | '/s/$schoolId/principals'
    | '/s/$schoolId/settings'
    | '/s/$schoolId/teachers'
    | '/s/$schoolId/teams'
    | '/c/$classId/'
    | '/s/$schoolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/account'
    | '/join'
    | '/settings'
    | '/'
    | '/c/$classId/assistant-teachers'
    | '/c/$classId/groups'
    | '/c/$classId/guardians'
    | '/c/$classId/invite'
    | '/c/$classId/members'
    | '/c/$classId/points'
    | '/c/$classId/settings'
    | '/c/$classId/students'
    | '/c/$classId/teachers'
    | '/s/$schoolId/admins'
    | '/s/$schoolId/classes'
    | '/s/$schoolId/invite'
    | '/s/$schoolId/members'
    | '/s/$schoolId/principals'
    | '/s/$schoolId/settings'
    | '/s/$schoolId/teachers'
    | '/s/$schoolId/teams'
    | '/c/$classId'
    | '/s/$schoolId'
  id:
    | '__root__'
    | '/_account'
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/_account/account'
    | '/_account/join'
    | '/_account/settings'
    | '/_account/'
    | '/_account/c/$classId'
    | '/_account/s/$schoolId'
    | '/_account/c/$classId/assistant-teachers'
    | '/_account/c/$classId/groups'
    | '/_account/c/$classId/guardians'
    | '/_account/c/$classId/invite'
    | '/_account/c/$classId/members'
    | '/_account/c/$classId/points'
    | '/_account/c/$classId/settings'
    | '/_account/c/$classId/students'
    | '/_account/c/$classId/teachers'
    | '/_account/s/$schoolId/admins'
    | '/_account/s/$schoolId/classes'
    | '/_account/s/$schoolId/invite'
    | '/_account/s/$schoolId/members'
    | '/_account/s/$schoolId/principals'
    | '/_account/s/$schoolId/settings'
    | '/_account/s/$schoolId/teachers'
    | '/_account/s/$schoolId/teams'
    | '/_account/c/$classId/'
    | '/_account/s/$schoolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  JoinShareRoute: typeof JoinShareRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-share': {
      id: '/join-share'
      path: '/join-share'
      fullPath: '/join-share'
      preLoaderRoute: typeof JoinShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account/': {
      id: '/_account/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/settings': {
      id: '/_account/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/join': {
      id: '/_account/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AccountJoinRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account': {
      id: '/_account/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountAccountRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/s/$schoolId': {
      id: '/_account/s/$schoolId'
      path: '/s/$schoolId'
      fullPath: '/s/$schoolId'
      preLoaderRoute: typeof AccountSSchoolIdRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/c/$classId': {
      id: '/_account/c/$classId'
      path: '/c/$classId'
      fullPath: '/c/$classId'
      preLoaderRoute: typeof AccountCClassIdRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/s/$schoolId/': {
      id: '/_account/s/$schoolId/'
      path: '/'
      fullPath: '/s/$schoolId/'
      preLoaderRoute: typeof AccountSSchoolIdIndexRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/c/$classId/': {
      id: '/_account/c/$classId/'
      path: '/'
      fullPath: '/c/$classId/'
      preLoaderRoute: typeof AccountCClassIdIndexRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/s/$schoolId/teams': {
      id: '/_account/s/$schoolId/teams'
      path: '/teams'
      fullPath: '/s/$schoolId/teams'
      preLoaderRoute: typeof AccountSSchoolIdTeamsRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/s/$schoolId/teachers': {
      id: '/_account/s/$schoolId/teachers'
      path: '/teachers'
      fullPath: '/s/$schoolId/teachers'
      preLoaderRoute: typeof AccountSSchoolIdTeachersRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/s/$schoolId/settings': {
      id: '/_account/s/$schoolId/settings'
      path: '/settings'
      fullPath: '/s/$schoolId/settings'
      preLoaderRoute: typeof AccountSSchoolIdSettingsRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/s/$schoolId/principals': {
      id: '/_account/s/$schoolId/principals'
      path: '/principals'
      fullPath: '/s/$schoolId/principals'
      preLoaderRoute: typeof AccountSSchoolIdPrincipalsRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/s/$schoolId/members': {
      id: '/_account/s/$schoolId/members'
      path: '/members'
      fullPath: '/s/$schoolId/members'
      preLoaderRoute: typeof AccountSSchoolIdMembersRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/s/$schoolId/invite': {
      id: '/_account/s/$schoolId/invite'
      path: '/invite'
      fullPath: '/s/$schoolId/invite'
      preLoaderRoute: typeof AccountSSchoolIdInviteRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/s/$schoolId/classes': {
      id: '/_account/s/$schoolId/classes'
      path: '/classes'
      fullPath: '/s/$schoolId/classes'
      preLoaderRoute: typeof AccountSSchoolIdClassesRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/s/$schoolId/admins': {
      id: '/_account/s/$schoolId/admins'
      path: '/admins'
      fullPath: '/s/$schoolId/admins'
      preLoaderRoute: typeof AccountSSchoolIdAdminsRouteImport
      parentRoute: typeof AccountSSchoolIdRouteRoute
    }
    '/_account/c/$classId/teachers': {
      id: '/_account/c/$classId/teachers'
      path: '/teachers'
      fullPath: '/c/$classId/teachers'
      preLoaderRoute: typeof AccountCClassIdTeachersRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/students': {
      id: '/_account/c/$classId/students'
      path: '/students'
      fullPath: '/c/$classId/students'
      preLoaderRoute: typeof AccountCClassIdStudentsRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/settings': {
      id: '/_account/c/$classId/settings'
      path: '/settings'
      fullPath: '/c/$classId/settings'
      preLoaderRoute: typeof AccountCClassIdSettingsRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/points': {
      id: '/_account/c/$classId/points'
      path: '/points'
      fullPath: '/c/$classId/points'
      preLoaderRoute: typeof AccountCClassIdPointsRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/members': {
      id: '/_account/c/$classId/members'
      path: '/members'
      fullPath: '/c/$classId/members'
      preLoaderRoute: typeof AccountCClassIdMembersRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/invite': {
      id: '/_account/c/$classId/invite'
      path: '/invite'
      fullPath: '/c/$classId/invite'
      preLoaderRoute: typeof AccountCClassIdInviteRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/guardians': {
      id: '/_account/c/$classId/guardians'
      path: '/guardians'
      fullPath: '/c/$classId/guardians'
      preLoaderRoute: typeof AccountCClassIdGuardiansRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/groups': {
      id: '/_account/c/$classId/groups'
      path: '/groups'
      fullPath: '/c/$classId/groups'
      preLoaderRoute: typeof AccountCClassIdGroupsRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/assistant-teachers': {
      id: '/_account/c/$classId/assistant-teachers'
      path: '/assistant-teachers'
      fullPath: '/c/$classId/assistant-teachers'
      preLoaderRoute: typeof AccountCClassIdAssistantTeachersRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
  }
}

interface AccountCClassIdRouteRouteChildren {
  AccountCClassIdAssistantTeachersRoute: typeof AccountCClassIdAssistantTeachersRoute
  AccountCClassIdGroupsRoute: typeof AccountCClassIdGroupsRoute
  AccountCClassIdGuardiansRoute: typeof AccountCClassIdGuardiansRoute
  AccountCClassIdInviteRoute: typeof AccountCClassIdInviteRoute
  AccountCClassIdMembersRoute: typeof AccountCClassIdMembersRoute
  AccountCClassIdPointsRoute: typeof AccountCClassIdPointsRoute
  AccountCClassIdSettingsRoute: typeof AccountCClassIdSettingsRoute
  AccountCClassIdStudentsRoute: typeof AccountCClassIdStudentsRoute
  AccountCClassIdTeachersRoute: typeof AccountCClassIdTeachersRoute
  AccountCClassIdIndexRoute: typeof AccountCClassIdIndexRoute
}

const AccountCClassIdRouteRouteChildren: AccountCClassIdRouteRouteChildren = {
  AccountCClassIdAssistantTeachersRoute: AccountCClassIdAssistantTeachersRoute,
  AccountCClassIdGroupsRoute: AccountCClassIdGroupsRoute,
  AccountCClassIdGuardiansRoute: AccountCClassIdGuardiansRoute,
  AccountCClassIdInviteRoute: AccountCClassIdInviteRoute,
  AccountCClassIdMembersRoute: AccountCClassIdMembersRoute,
  AccountCClassIdPointsRoute: AccountCClassIdPointsRoute,
  AccountCClassIdSettingsRoute: AccountCClassIdSettingsRoute,
  AccountCClassIdStudentsRoute: AccountCClassIdStudentsRoute,
  AccountCClassIdTeachersRoute: AccountCClassIdTeachersRoute,
  AccountCClassIdIndexRoute: AccountCClassIdIndexRoute,
}

const AccountCClassIdRouteRouteWithChildren =
  AccountCClassIdRouteRoute._addFileChildren(AccountCClassIdRouteRouteChildren)

interface AccountSSchoolIdRouteRouteChildren {
  AccountSSchoolIdAdminsRoute: typeof AccountSSchoolIdAdminsRoute
  AccountSSchoolIdClassesRoute: typeof AccountSSchoolIdClassesRoute
  AccountSSchoolIdInviteRoute: typeof AccountSSchoolIdInviteRoute
  AccountSSchoolIdMembersRoute: typeof AccountSSchoolIdMembersRoute
  AccountSSchoolIdPrincipalsRoute: typeof AccountSSchoolIdPrincipalsRoute
  AccountSSchoolIdSettingsRoute: typeof AccountSSchoolIdSettingsRoute
  AccountSSchoolIdTeachersRoute: typeof AccountSSchoolIdTeachersRoute
  AccountSSchoolIdTeamsRoute: typeof AccountSSchoolIdTeamsRoute
  AccountSSchoolIdIndexRoute: typeof AccountSSchoolIdIndexRoute
}

const AccountSSchoolIdRouteRouteChildren: AccountSSchoolIdRouteRouteChildren = {
  AccountSSchoolIdAdminsRoute: AccountSSchoolIdAdminsRoute,
  AccountSSchoolIdClassesRoute: AccountSSchoolIdClassesRoute,
  AccountSSchoolIdInviteRoute: AccountSSchoolIdInviteRoute,
  AccountSSchoolIdMembersRoute: AccountSSchoolIdMembersRoute,
  AccountSSchoolIdPrincipalsRoute: AccountSSchoolIdPrincipalsRoute,
  AccountSSchoolIdSettingsRoute: AccountSSchoolIdSettingsRoute,
  AccountSSchoolIdTeachersRoute: AccountSSchoolIdTeachersRoute,
  AccountSSchoolIdTeamsRoute: AccountSSchoolIdTeamsRoute,
  AccountSSchoolIdIndexRoute: AccountSSchoolIdIndexRoute,
}

const AccountSSchoolIdRouteRouteWithChildren =
  AccountSSchoolIdRouteRoute._addFileChildren(
    AccountSSchoolIdRouteRouteChildren,
  )

interface AccountRouteRouteChildren {
  AccountAccountRoute: typeof AccountAccountRoute
  AccountJoinRoute: typeof AccountJoinRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountCClassIdRouteRoute: typeof AccountCClassIdRouteRouteWithChildren
  AccountSSchoolIdRouteRoute: typeof AccountSSchoolIdRouteRouteWithChildren
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAccountRoute: AccountAccountRoute,
  AccountJoinRoute: AccountJoinRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountCClassIdRouteRoute: AccountCClassIdRouteRouteWithChildren,
  AccountSSchoolIdRouteRoute: AccountSSchoolIdRouteRouteWithChildren,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AccountRouteRoute: AccountRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  JoinShareRoute: JoinShareRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
