/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinShareRouteImport } from './routes/join-share'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteRouteImport } from './routes/_account/route'
import { Route as AccountIndexRouteImport } from './routes/_account/index'
import { Route as AccountJoinRouteImport } from './routes/_account/join'
import { Route as AccountCClassIdRouteImport } from './routes/_account/c.$classId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinShareRoute = JoinShareRouteImport.update({
  id: '/join-share',
  path: '/join-share',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountJoinRoute = AccountJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountCClassIdRoute = AccountCClassIdRouteImport.update({
  id: '/c/$classId',
  path: '/c/$classId',
  getParentRoute: () => AccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AccountIndexRoute
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/join': typeof AccountJoinRoute
  '/c/$classId': typeof AccountCClassIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/join': typeof AccountJoinRoute
  '/': typeof AccountIndexRoute
  '/c/$classId': typeof AccountCClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_account': typeof AccountRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_account/join': typeof AccountJoinRoute
  '/_account/': typeof AccountIndexRoute
  '/_account/c/$classId': typeof AccountCClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/join'
    | '/c/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/join'
    | '/'
    | '/c/$classId'
  id:
    | '__root__'
    | '/_account'
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/_account/join'
    | '/_account/'
    | '/_account/c/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  JoinShareRoute: typeof JoinShareRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-share': {
      id: '/join-share'
      path: '/join-share'
      fullPath: '/join-share'
      preLoaderRoute: typeof JoinShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account/': {
      id: '/_account/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/join': {
      id: '/_account/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AccountJoinRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/c/$classId': {
      id: '/_account/c/$classId'
      path: '/c/$classId'
      fullPath: '/c/$classId'
      preLoaderRoute: typeof AccountCClassIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountJoinRoute: typeof AccountJoinRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountCClassIdRoute: typeof AccountCClassIdRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountJoinRoute: AccountJoinRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountCClassIdRoute: AccountCClassIdRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AccountRouteRoute: AccountRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  JoinShareRoute: JoinShareRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
