/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinShareRouteImport } from './routes/join-share'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteRouteImport } from './routes/_account/route'
import { Route as AccountIndexRouteImport } from './routes/_account/index'
import { Route as AccountSettingsRouteImport } from './routes/_account/settings'
import { Route as AccountJoinRouteImport } from './routes/_account/join'
import { Route as AccountAccountRouteImport } from './routes/_account/account'
import { Route as AccountCClassIdRouteRouteImport } from './routes/_account/c.$classId/route'
import { Route as AccountCClassIdIndexRouteImport } from './routes/_account/c.$classId/index'
import { Route as AccountCClassIdStudentsRouteImport } from './routes/_account/c.$classId/students'
import { Route as AccountCClassIdSettingsRouteImport } from './routes/_account/c.$classId/settings'
import { Route as AccountCClassIdPointsRouteImport } from './routes/_account/c.$classId/points'
import { Route as AccountCClassIdMembersRouteImport } from './routes/_account/c.$classId/members'
import { Route as AccountCClassIdInviteRouteImport } from './routes/_account/c.$classId/invite'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinShareRoute = JoinShareRouteImport.update({
  id: '/join-share',
  path: '/join-share',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountJoinRoute = AccountJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAccountRoute = AccountAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountCClassIdRouteRoute = AccountCClassIdRouteRouteImport.update({
  id: '/c/$classId',
  path: '/c/$classId',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountCClassIdIndexRoute = AccountCClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdStudentsRoute = AccountCClassIdStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdSettingsRoute = AccountCClassIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdPointsRoute = AccountCClassIdPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdMembersRoute = AccountCClassIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)
const AccountCClassIdInviteRoute = AccountCClassIdInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AccountCClassIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AccountIndexRoute
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AccountAccountRoute
  '/join': typeof AccountJoinRoute
  '/settings': typeof AccountSettingsRoute
  '/c/$classId': typeof AccountCClassIdRouteRouteWithChildren
  '/c/$classId/invite': typeof AccountCClassIdInviteRoute
  '/c/$classId/members': typeof AccountCClassIdMembersRoute
  '/c/$classId/points': typeof AccountCClassIdPointsRoute
  '/c/$classId/settings': typeof AccountCClassIdSettingsRoute
  '/c/$classId/students': typeof AccountCClassIdStudentsRoute
  '/c/$classId/': typeof AccountCClassIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account': typeof AccountAccountRoute
  '/join': typeof AccountJoinRoute
  '/settings': typeof AccountSettingsRoute
  '/': typeof AccountIndexRoute
  '/c/$classId/invite': typeof AccountCClassIdInviteRoute
  '/c/$classId/members': typeof AccountCClassIdMembersRoute
  '/c/$classId/points': typeof AccountCClassIdPointsRoute
  '/c/$classId/settings': typeof AccountCClassIdSettingsRoute
  '/c/$classId/students': typeof AccountCClassIdStudentsRoute
  '/c/$classId': typeof AccountCClassIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_account': typeof AccountRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/join-share': typeof JoinShareRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_account/account': typeof AccountAccountRoute
  '/_account/join': typeof AccountJoinRoute
  '/_account/settings': typeof AccountSettingsRoute
  '/_account/': typeof AccountIndexRoute
  '/_account/c/$classId': typeof AccountCClassIdRouteRouteWithChildren
  '/_account/c/$classId/invite': typeof AccountCClassIdInviteRoute
  '/_account/c/$classId/members': typeof AccountCClassIdMembersRoute
  '/_account/c/$classId/points': typeof AccountCClassIdPointsRoute
  '/_account/c/$classId/settings': typeof AccountCClassIdSettingsRoute
  '/_account/c/$classId/students': typeof AccountCClassIdStudentsRoute
  '/_account/c/$classId/': typeof AccountCClassIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/account'
    | '/join'
    | '/settings'
    | '/c/$classId'
    | '/c/$classId/invite'
    | '/c/$classId/members'
    | '/c/$classId/points'
    | '/c/$classId/settings'
    | '/c/$classId/students'
    | '/c/$classId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/account'
    | '/join'
    | '/settings'
    | '/'
    | '/c/$classId/invite'
    | '/c/$classId/members'
    | '/c/$classId/points'
    | '/c/$classId/settings'
    | '/c/$classId/students'
    | '/c/$classId'
  id:
    | '__root__'
    | '/_account'
    | '/$'
    | '/join-share'
    | '/login'
    | '/unauthorized'
    | '/_account/account'
    | '/_account/join'
    | '/_account/settings'
    | '/_account/'
    | '/_account/c/$classId'
    | '/_account/c/$classId/invite'
    | '/_account/c/$classId/members'
    | '/_account/c/$classId/points'
    | '/_account/c/$classId/settings'
    | '/_account/c/$classId/students'
    | '/_account/c/$classId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  JoinShareRoute: typeof JoinShareRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-share': {
      id: '/join-share'
      path: '/join-share'
      fullPath: '/join-share'
      preLoaderRoute: typeof JoinShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account/': {
      id: '/_account/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/settings': {
      id: '/_account/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/join': {
      id: '/_account/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AccountJoinRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account': {
      id: '/_account/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountAccountRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/c/$classId': {
      id: '/_account/c/$classId'
      path: '/c/$classId'
      fullPath: '/c/$classId'
      preLoaderRoute: typeof AccountCClassIdRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/c/$classId/': {
      id: '/_account/c/$classId/'
      path: '/'
      fullPath: '/c/$classId/'
      preLoaderRoute: typeof AccountCClassIdIndexRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/students': {
      id: '/_account/c/$classId/students'
      path: '/students'
      fullPath: '/c/$classId/students'
      preLoaderRoute: typeof AccountCClassIdStudentsRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/settings': {
      id: '/_account/c/$classId/settings'
      path: '/settings'
      fullPath: '/c/$classId/settings'
      preLoaderRoute: typeof AccountCClassIdSettingsRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/points': {
      id: '/_account/c/$classId/points'
      path: '/points'
      fullPath: '/c/$classId/points'
      preLoaderRoute: typeof AccountCClassIdPointsRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/members': {
      id: '/_account/c/$classId/members'
      path: '/members'
      fullPath: '/c/$classId/members'
      preLoaderRoute: typeof AccountCClassIdMembersRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
    '/_account/c/$classId/invite': {
      id: '/_account/c/$classId/invite'
      path: '/invite'
      fullPath: '/c/$classId/invite'
      preLoaderRoute: typeof AccountCClassIdInviteRouteImport
      parentRoute: typeof AccountCClassIdRouteRoute
    }
  }
}

interface AccountCClassIdRouteRouteChildren {
  AccountCClassIdInviteRoute: typeof AccountCClassIdInviteRoute
  AccountCClassIdMembersRoute: typeof AccountCClassIdMembersRoute
  AccountCClassIdPointsRoute: typeof AccountCClassIdPointsRoute
  AccountCClassIdSettingsRoute: typeof AccountCClassIdSettingsRoute
  AccountCClassIdStudentsRoute: typeof AccountCClassIdStudentsRoute
  AccountCClassIdIndexRoute: typeof AccountCClassIdIndexRoute
}

const AccountCClassIdRouteRouteChildren: AccountCClassIdRouteRouteChildren = {
  AccountCClassIdInviteRoute: AccountCClassIdInviteRoute,
  AccountCClassIdMembersRoute: AccountCClassIdMembersRoute,
  AccountCClassIdPointsRoute: AccountCClassIdPointsRoute,
  AccountCClassIdSettingsRoute: AccountCClassIdSettingsRoute,
  AccountCClassIdStudentsRoute: AccountCClassIdStudentsRoute,
  AccountCClassIdIndexRoute: AccountCClassIdIndexRoute,
}

const AccountCClassIdRouteRouteWithChildren =
  AccountCClassIdRouteRoute._addFileChildren(AccountCClassIdRouteRouteChildren)

interface AccountRouteRouteChildren {
  AccountAccountRoute: typeof AccountAccountRoute
  AccountJoinRoute: typeof AccountJoinRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountCClassIdRouteRoute: typeof AccountCClassIdRouteRouteWithChildren
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAccountRoute: AccountAccountRoute,
  AccountJoinRoute: AccountJoinRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountCClassIdRouteRoute: AccountCClassIdRouteRouteWithChildren,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AccountRouteRoute: AccountRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  JoinShareRoute: JoinShareRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
